#spring.data.mongodb.uri=mongodb://localhost/nash-internships -LOCAL
#mongodb+srv://admin:admin@nash-internships.mtxoj7o.mongodb.net/nash-internships -REMOTO
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@nash-internships.mtxoj7o.mongodb.net/nash-internships
#jwt.secret = secret #jwt.expiration = 36000
jwt:
  secret: secret
  expiration: 36000

azure:
  storage:
    container:
      name: archivos
    connection:
      string: DefaultEndpointsProtocol=https;AccountName=nashinternships;AccountKey=FPiPHqSva2xm/sraPkF9SusoO/RG4V0SyoljljqrLAgp3hg3CqMUWufhMdvngx6WVkQsfnjYMQET+AStgQWjkg==;EndpointSuffix=core.windows.net
